coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: 90%
        threshold: 0%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  require_changes: true
