name: 'Setup ML Environment'
description: 'Shared setup for ML Python environment with caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  install-dev-deps:
    description: 'Install development dependencies (requirements-dev.txt)'
    required: false
    default: 'false'
  supabase-url:
    description: 'Supabase URL for environment configuration'
    required: false
  supabase-key:
    description: 'Supabase service role key'
    required: false
  database-url:
    description: 'Direct database connection URL'
    required: false
  alpaca-api-key:
    description: 'Alpaca API key'
    required: false
  alpaca-api-secret:
    description: 'Alpaca API secret'
    required: false
  tradier-api-key:
    description: 'Tradier API key for options data'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: 'ml/requirements.txt'

    - name: Install TA-Lib (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update -y
        sudo apt-get install -y build-essential wget
        wget -q http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure --prefix=/usr
        make -j"$(nproc)"
        sudo make install

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ml/requirements.txt

    - name: Install adaptive_supertrend dependencies
      shell: bash
      run: |
        if [ -f adaptive_supertrend/requirements.txt ]; then
          pip install -r adaptive_supertrend/requirements.txt
          # Install package in editable mode so module imports resolve during jobs
          pip install -e adaptive_supertrend
        fi

    - name: Export PYTHONPATH for adaptive_supertrend
      shell: bash
      run: |
        echo "PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}$(pwd)/adaptive_supertrend" >> $GITHUB_ENV

    - name: Install development dependencies
      if: inputs.install-dev-deps == 'true'
      shell: bash
      run: |
        pip install -r ml/requirements-dev.txt

    - name: Configure environment
      if: inputs.supabase-url != ''
      shell: bash
      run: |
        cd ml
        # Strip whitespace and newlines from secrets to prevent HTTP header errors
        SUPABASE_URL=$(echo -n "${{ inputs.supabase-url }}" | xargs)
        SUPABASE_KEY=$(echo -n "${{ inputs.supabase-key }}" | xargs)
        DATABASE_URL=$(echo -n "${{ inputs.database-url }}" | xargs)
        ALPACA_API_KEY=$(echo -n "${{ inputs.alpaca-api-key }}" | xargs)
        ALPACA_API_SECRET=$(echo -n "${{ inputs.alpaca-api-secret }}" | xargs)
        TRADIER_API_KEY=$(echo -n "${{ inputs.tradier-api-key }}" | xargs)
        
        cat > .env << EOF
        SUPABASE_URL=${SUPABASE_URL}
        SUPABASE_KEY=${SUPABASE_KEY}
        DATABASE_URL=${DATABASE_URL}
        ALPACA_API_KEY=${ALPACA_API_KEY}
        ALPACA_API_SECRET=${ALPACA_API_SECRET}
        TRADIER_API_KEY=${TRADIER_API_KEY}
        EOF
