name: 'Setup ML Environment'
description: 'Shared setup for ML Python environment with caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  install-dev-deps:
    description: 'Install development dependencies (requirements-dev.txt)'
    required: false
    default: 'false'
  supabase-url:
    description: 'Supabase URL for environment configuration'
    required: false
  supabase-key:
    description: 'Supabase service role key'
    required: false
  database-url:
    description: 'Direct database connection URL'
    required: false
  alpaca-api-key:
    description: 'Alpaca API key'
    required: false
  alpaca-api-secret:
    description: 'Alpaca API secret'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: 'ml/requirements.txt'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ml/requirements.txt

    - name: Install development dependencies
      if: inputs.install-dev-deps == 'true'
      shell: bash
      run: |
        pip install -r ml/requirements-dev.txt

    - name: Configure environment
      if: inputs.supabase-url != ''
      shell: bash
      run: |
        cd ml
        cat > .env << EOF
        SUPABASE_URL=${{ inputs.supabase-url }}
        SUPABASE_KEY=${{ inputs.supabase-key }}
        DATABASE_URL=${{ inputs.database-url }}
        ALPACA_API_KEY=${{ inputs.alpaca-api-key }}
        ALPACA_API_SECRET=${{ inputs.alpaca-api-secret }}
        EOF
