ALTER TABLE ml_forecasts ADD COLUMN IF NOT EXISTS q10 NUMERIC(12,4);
ALTER TABLE ml_forecasts ADD COLUMN IF NOT EXISTS q25 NUMERIC(12,4);
ALTER TABLE ml_forecasts ADD COLUMN IF NOT EXISTS q50 NUMERIC(12,4);
ALTER TABLE ml_forecasts ADD COLUMN IF NOT EXISTS q75 NUMERIC(12,4);
ALTER TABLE ml_forecasts ADD COLUMN IF NOT EXISTS q90 NUMERIC(12,4);
